import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import TransitionWrapper from "@/components/pagetransition/TransitionWrapper";
import LenisScroll from "./utils/Lenis";


const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} antialiased`}
      >
        <LenisScroll>
        <TransitionWrapper>
          <Nav />
          {children}
        </TransitionWrapper>
        </LenisScroll>
      </body>
    </html>
  );
}
